services:

  mysql:
    build:
      context: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - flask-sql


  app:
    build:
      context: project
    ports:
      - "5000"
    environment:
      - FLASK_APP=__init__.py
      - FLASK_ENV=development
    volumes:
      - ./project:/code
    #develop:
      #watch:
        #- action: sync
          #path: ./project/
          #target: /code
    depends_on:
      mysql:
         condition: service_healthy
    networks:
      - flask-sql
    command: gunicorn --bind 0.0.0.0:5000 --reload __init__:app
    

  nginx:
    build: ./nginxproxy # Build from the Dockerfile in the nginx-proxy directory
    ports:
      - "80:80" # Expose Nginx on port 80
      - "443:443" # Expose Nginx on port 443 if you set up SSL
    volumes:
      #Copy over some internal files idfk
      - ./project/templates/includes/rate_limit.html:/usr/share/nginx/html/rate_limit.html:ro
      # Optional: Mount a volume for Nginx/ModSecurity logs to persist them
      - ./nginxproxy/custom_modsec_rules:/etc/nginx/modsec/custom_modsec_rules # If you create custom rules
      - ./certs:/etc/nginx/certs:ro 
      - ./modsec_logs:/var/log/nginx/modsec_audit_data 
      - ./nginx_logs:/var/log/nginx
    depends_on:
      - app # Nginx depends on the Flask app being ready
    restart: always
    networks:
      - flask-sql
  #nginx:
    #image: nginx:latest
    #volumes:
      #- ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./certs:/etc/nginx/certs:ro 
    #depends_on:
      #- app
    #ports:
      #- "80:80"
      #- "443:443"
    
    #restart: always
    #networks:
      #- flask-sql



volumes:
  two-tier:
networks:
  flask-sql:
    driver: bridge