services:
  app:
    build:
      context: project
    ports:
      - "5000"
    develop:
      watch:
        - action: sync
          path: ./project/
          target: /code
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"
    