[default]
host = flask-app

# Nginx Access Logs
[monitor:///var/log/nginx/access.log]
index = web_access
sourcetype = nginx:plus:access
disabled = false

# Nginx Error Logs
[monitor:///var/log/nginx/error.log]
index = web_errors
sourcetype = nginx:plus:error
disabled = false

# ModSecurity Audit Log (main file)
[monitor:///var/log/nginx/modsec_audit.log]
index = security
sourcetype = modsecurity
disabled = false

# ModSecurity Audit Data Directory (if exists)
[monitor:///var/log/nginx/modsec_audit_data]
index = security
sourcetype = modsecurity:audit
disabled = false
recursive = true

# ModSecurity logs from modsec_logs directory
[monitor:///var/log/nginx/modsec_audit_data]
index = security
sourcetype = modsecurity:concurrent
disabled = false
recursive = true

[splunktcp://9997]
disabled = 0
