[default]
host = flask-app

[monitor:///var/log/nginx/access.log]
index = web_access
sourcetype = nginx_access

[monitor:///var/log/nginx/error.log]
index = web_errors
sourcetype = nginx_error

[monitor:///var/log/app/modsec_audit.log]
index = security
sourcetype = modsec_audit

[monitor:///var/log/app/error.log]
index = app_errors
sourcetype = python_error

[monitor:///var/log/app/user_actions.log]
index = user_activity
sourcetype = user_actions
[splunktcp://9997]
disabled = 0
