
[httpServer]
mgmtMode = auto

[sslConfig]
sslPassword = $7$PWVpXynvbYsMqtpdL4fm0inq21SCMyGAiV+zj6LscD/mXyL71FeICA==

[general]
pass4SymmKey = $7$y4HTf9HGQmLk+44PkuT5fPzi9DXuDTFKvRaumk0HrgYUApE1KI6lpQ==

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
